//! Managed `.gitignore` block: marker parsing, block build/normalization,
//! merge, diff, and write — a byte-level port of `internal/gitignore`.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub const START_MARKER: &str = "# BEGIN genignore";
pub const END_MARKER: &str = "# END genignore";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileAction {
    Created,
    Updated,
    NoOp,
    DryRun,
}

impl FileAction {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Updated => "updated",
            Self::NoOp => "no-op",
            Self::DryRun => "dry-run",
        }
    }
}

pub struct Manager {
    pub path: PathBuf,
}

pub struct Preview {
    pub action: FileAction,
    pub diff: String,
}

const REQUIRED_ENV_RULES: [&str; 4] = [".env", ".env.*", "!.env.example", "!.env.ci"];

const GENERATED_COMMENT_PREFIXES: [&str; 5] = [
    "# Created by https://www.toptal.com/developers/gitignore/api/",
    "# Edit at https://www.toptal.com/developers/gitignore?templates=",
    "# End of https://www.toptal.com/developers/gitignore/api/",
    "# Source: github/gitignore/",
    "# Source: https://raw.githubusercontent.com/github/gitignore/",
];

impl Manager {
    pub fn new(cwd: &Path) -> Manager {
        Manager {
            path: cwd.join(".gitignore"),
        }
    }

    pub fn read_managed_providers(&self) -> Result<Option<Vec<String>>, String> {
        match fs::read_to_string(&self.path) {
            Ok(content) => Ok(parse_managed_providers(&content)),
            Err(err) if err.kind() == io::ErrorKind::NotFound => Ok(None),
            Err(err) => Err(format!("read .gitignore: {}", err)),
        }
    }

    pub fn preview_managed_block(&self, block: &str) -> Result<Preview, String> {
        let change = self.plan_change(block)?;
        Ok(Preview {
            action: change.action,
            diff: managed_block_diff(&change.current_block, block),
        })
    }

    pub fn upsert_managed_block(&self, block: &str, dry_run: bool) -> Result<FileAction, String> {
        let change = self.plan_change(block)?;
        if change.action == FileAction::Created {
            if dry_run {
                return Ok(FileAction::DryRun);
            }
            fs::write(&self.path, block.as_bytes())
                .map_err(|e| format!("create .gitignore: {}", e))?;
            return Ok(FileAction::Created);
        }
        if dry_run {
            return Ok(FileAction::DryRun);
        }
        if change.action == FileAction::NoOp {
            return Ok(FileAction::NoOp);
        }
        fs::write(&self.path, change.updated_content.as_bytes())
            .map_err(|e| format!("update .gitignore: {}", e))?;
        Ok(FileAction::Updated)
    }

    fn plan_change(&self, block: &str) -> Result<PlannedChange, String> {
        let content = match fs::read(&self.path) {
            Ok(c) => c,
            Err(err) if err.kind() == io::ErrorKind::NotFound => {
                return Ok(PlannedChange {
                    action: FileAction::Created,
                    current_block: String::new(),
                    updated_content: block.to_string(),
                });
            }
            Err(err) => return Err(format!("read .gitignore: {}", err)),
        };
        let existing = String::from_utf8_lossy(&content).into_owned();
        let current_block = current_managed_block(&existing)?;
        let updated = merge_managed_block(&existing, block)?;
        if updated == existing {
            return Ok(PlannedChange {
                action: FileAction::NoOp,
                current_block,
                updated_content: updated,
            });
        }
        Ok(PlannedChange {
            action: FileAction::Updated,
            current_block,
            updated_content: updated,
        })
    }
}

struct PlannedChange {
    action: FileAction,
    current_block: String,
    updated_content: String,
}

pub fn build_managed_block(
    providers: &[String],
    metadata: &[String],
    template: &str,
    extra_rule_sources: &[Vec<String>],
) -> String {
    let normalized = normalize_template(template, extra_rule_sources);
    let mut lines = vec![
        START_MARKER.to_string(),
        "# Generated by genignore. Do not edit between these markers.".to_string(),
        format!("# Providers: {}", providers.join(",")),
    ];
    for line in metadata {
        if line.trim().is_empty() {
            continue;
        }
        lines.push(line.clone());
    }
    lines.push(normalized);
    lines.push(END_MARKER.to_string());
    lines.push(String::new());
    lines.join("\n")
}

fn normalize_template(template: &str, extra_rule_sources: &[Vec<String>]) -> String {
    let lines: Vec<&str> = template.split('\n').collect();
    let mut normalized: Vec<String> = Vec::with_capacity(lines.len());
    let mut appended: Vec<String> = Vec::new();
    let mut env_rules: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let mut rule_lines: std::collections::HashSet<String> = std::collections::HashSet::new();

    for line in &lines {
        if is_generated_source_comment(line) {
            continue;
        }
        if let Some(canonical) = canonicalize_env_rule(line) {
            env_rules.insert(canonical);
            continue;
        }
        if is_rule_line(line) {
            rule_lines.insert(line.trim().to_string());
        }
        normalized.push((*line).to_string());
    }

    for source in extra_rule_sources {
        for line in source {
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }
            if let Some(canonical) = canonicalize_env_rule(line) {
                env_rules.insert(canonical);
                continue;
            }
            if rule_lines.contains(trimmed) {
                continue;
            }
            rule_lines.insert(trimmed.to_string());
            appended.push(trimmed.to_string());
        }
    }

    for required in REQUIRED_ENV_RULES {
        env_rules.insert(required.to_string());
    }

    let mut out = trim_trailing_blank_lines(normalized);
    if !appended.is_empty() {
        if !out.is_empty() && !out.last().unwrap().trim().is_empty() {
            out.push(String::new());
        }
        out.extend(appended);
    }

    let ordered_env = ordered_env_rules(&env_rules);
    if !ordered_env.is_empty() {
        if !out.is_empty() && !out.last().unwrap().trim().is_empty() {
            out.push(String::new());
        }
        out.extend(ordered_env.iter().map(|s| s.to_string()));
    }

    out.join("\n").trim_matches('\n').to_string()
}

fn ordered_env_rules(env_rules: &std::collections::BTreeSet<String>) -> Vec<String> {
    let mut additional: Vec<String> = env_rules
        .iter()
        .filter(|line| !is_required_env_rule(line) && !conflicts_with_required_env_rule(line))
        .cloned()
        .collect();
    additional.sort();
    let mut ordered: Vec<String> = REQUIRED_ENV_RULES.iter().map(|s| s.to_string()).collect();
    ordered.extend(additional);
    ordered
}

fn is_required_env_rule(line: &str) -> bool {
    REQUIRED_ENV_RULES.contains(&line)
}

fn conflicts_with_required_env_rule(line: &str) -> bool {
    matches!(line, "!.env" | "!.env.*" | ".env.example" | ".env.ci")
}

fn trim_trailing_blank_lines(lines: Vec<String>) -> Vec<String> {
    let mut end = lines.len();
    while end > 0 && lines[end - 1].trim().is_empty() {
        end -= 1;
    }
    lines[..end].to_vec()
}

fn canonicalize_env_rule(line: &str) -> Option<String> {
    if !is_rule_line(line) {
        return None;
    }
    let mut trimmed = line.trim().to_string();
    let negated = trimmed.starts_with('!');
    if negated {
        trimmed = trimmed[1..].to_string();
    }
    if let Some(rest) = trimmed.strip_prefix('/') {
        trimmed = rest.to_string();
    }
    if !trimmed.starts_with(".env") {
        return None;
    }
    Some(if negated {
        format!("!{}", trimmed)
    } else {
        trimmed
    })
}

fn is_generated_source_comment(line: &str) -> bool {
    let trimmed = line.trim();
    if !trimmed.starts_with("# ") {
        return false;
    }
    GENERATED_COMMENT_PREFIXES
        .iter()
        .any(|prefix| trimmed.starts_with(prefix))
}

fn is_rule_line(line: &str) -> bool {
    let trimmed = line.trim();
    !trimmed.is_empty() && !trimmed.starts_with('#')
}

pub fn parse_managed_providers(content: &str) -> Option<Vec<String>> {
    let start = content.find(START_MARKER)?;
    let end = content.find(END_MARKER)?;
    if end < start {
        return None;
    }
    let block = &content[start..end];
    for line in block.split('\n') {
        if let Some(csv) = line.strip_prefix("# Providers: ") {
            if csv.is_empty() {
                return None;
            }
            return Some(csv.split(',').map(|s| s.to_string()).collect());
        }
    }
    None
}

fn marker_bounds(content: &str) -> Result<Option<(usize, usize)>, String> {
    let start_count = content.matches(START_MARKER).count();
    let end_count = content.matches(END_MARKER).count();
    if start_count == 0 && end_count == 0 {
        return Ok(None);
    }
    if start_count != 1 || end_count != 1 {
        return Err(malformed_markers_error());
    }
    let start = content.find(START_MARKER).unwrap();
    let mut end = content.find(END_MARKER).unwrap();
    if end < start {
        return Err(malformed_markers_error());
    }
    end += END_MARKER.len();
    if end < content.len() && content.as_bytes()[end] == b'\n' {
        end += 1;
    }
    Ok(Some((start, end)))
}

fn malformed_markers_error() -> String {
    format!(
        "malformed managed markers in .gitignore: ensure exactly one {:?} and one {:?} in order",
        START_MARKER, END_MARKER
    )
}

fn merge_managed_block(existing: &str, block: &str) -> Result<String, String> {
    match marker_bounds(existing)? {
        None => {
            if existing.is_empty() {
                Ok(block.to_string())
            } else if block.ends_with('\n') {
                Ok(format!("{}{}", block, existing))
            } else {
                Ok(format!("{}\n{}", block, existing))
            }
        }
        Some((start, end)) => Ok(format!(
            "{}{}{}",
            &existing[..start],
            block,
            &existing[end..]
        )),
    }
}

fn current_managed_block(content: &str) -> Result<String, String> {
    match marker_bounds(content)? {
        None => Ok(String::new()),
        Some((start, end)) => Ok(content[start..end].to_string()),
    }
}

fn managed_block_diff(current_block: &str, next_block: &str) -> String {
    if current_block == next_block {
        return String::new();
    }
    let mut lines = vec![
        "--- .gitignore".to_string(),
        "+++ .gitignore".to_string(),
        "@@ managed-block @@".to_string(),
    ];
    for line in diff_lines(current_block) {
        lines.push(format!("-{}", line));
    }
    for line in diff_lines(next_block) {
        lines.push(format!("+{}", line));
    }
    lines.join("\n")
}

fn diff_lines(content: &str) -> Vec<String> {
    let trimmed = content.strip_suffix('\n').unwrap_or(content);
    if trimmed.is_empty() {
        return Vec::new();
    }
    trimmed.split('\n').map(|s| s.to_string()).collect()
}
