package gitignore

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const noisyToptalTemplate = `# Created by https://www.toptal.com/developers/gitignore/api/go,macos
# Edit at https://www.toptal.com/developers/gitignore?templates=go,macos

### Go ###
# If you prefer the allow list template instead of the deny list, see community template:
# https://github.com/github/gitignore/blob/main/community/Golang/Go.AllowList.gitignore
#
# Binaries for programs and plugins
*.exe

### macOS ###
.DS_Store

# End of https://www.toptal.com/developers/gitignore/api/go,macos
`

func TestBuildManagedBlockStripsToptalBoilerplateComments(t *testing.T) {
	t.Parallel()

	block := BuildManagedBlock([]string{"go", "macos"}, noisyToptalTemplate)

	for _, unwanted := range []string{
		"# Created by https://www.toptal.com/developers/gitignore/api/go,macos",
		"# Edit at https://www.toptal.com/developers/gitignore?templates=go,macos",
		"# End of https://www.toptal.com/developers/gitignore/api/go,macos",
	} {
		if strings.Contains(block, unwanted) {
			t.Fatalf("expected managed block to strip %q\n%s", unwanted, block)
		}
	}

	for _, wanted := range []string{
		StartMarker,
		"# Generated by genignore. Do not edit between these markers.",
		"# Providers: go,macos",
		"### Go ###",
		"# Binaries for programs and plugins",
		"*.exe",
		"### macOS ###",
		".DS_Store",
		EndMarker,
	} {
		if !strings.Contains(block, wanted) {
			t.Fatalf("expected managed block to preserve %q\n%s", wanted, block)
		}
	}
}

func TestBuildManagedBlockIsStableForCleanTemplate(t *testing.T) {
	t.Parallel()

	cleanTemplate := strings.Join([]string{
		"### Go ###",
		"bin/",
		"",
		"### macOS ###",
		".DS_Store",
		"",
	}, "\n")

	first := BuildManagedBlock([]string{"go", "macos"}, cleanTemplate)
	second := BuildManagedBlock([]string{"go", "macos"}, cleanTemplate)

	if first != second {
		t.Fatalf("expected stable managed block output\nfirst:\n%s\nsecond:\n%s", first, second)
	}
}

func TestUpsertCreatesFileWhenMissing(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	m := NewManager(dir)
	block := BuildManagedBlock([]string{"node"}, "node_modules/")

	action, err := m.UpsertManagedBlock(block, false)
	if err != nil {
		t.Fatalf("upsert returned error: %v", err)
	}
	if action != FileActionCreated {
		t.Fatalf("expected created action, got %s", action)
	}
	content, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	if !strings.Contains(string(content), StartMarker) {
		t.Fatalf("expected managed block in file")
	}
}

func TestUpsertPrependsWhenNoMarkers(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	if err := os.WriteFile(path, []byte("*.log\n"), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"node"}, "node_modules/")
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}
	content, _ := os.ReadFile(path)
	value := string(content)
	if !strings.HasPrefix(value, StartMarker) {
		t.Fatalf("expected block at top")
	}
	if !strings.Contains(value, "*.log") {
		t.Fatalf("expected existing content to remain")
	}
}

func TestUpsertPreservesLeadingBlankLinesWhenNoMarkers(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := "\n\n*.log\n"
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"node"}, "node_modules/")
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	want := block + seed
	if string(content) != want {
		t.Fatalf("expected existing content preserved exactly\nwant:\n%q\n got:\n%q", want, string(content))
	}
}

func TestUpsertReplacesOnlyManagedRegion(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		"before",
		StartMarker,
		"old",
		EndMarker,
		"after",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"go"}, "bin/")
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}
	content, _ := os.ReadFile(path)
	value := string(content)
	if !strings.Contains(value, "before") || !strings.Contains(value, "after") {
		t.Fatalf("expected content outside block untouched")
	}
	if strings.Contains(value, "old") {
		t.Fatalf("expected old block content replaced")
	}
}

func TestUpsertRejectsMalformedMarkers(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		"before",
		StartMarker,
		"old",
		"after",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"go"}, "bin/")
	if _, err := m.UpsertManagedBlock(block, false); err == nil {
		t.Fatalf("expected malformed marker error")
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	if string(content) != seed {
		t.Fatalf("malformed input should remain unchanged")
	}
}

func TestUpsertIsIdempotentForEquivalentRun(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	m := NewManager(dir)
	block := BuildManagedBlock([]string{"go", "node"}, "bin/\nnode_modules/\n")

	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("first upsert failed: %v", err)
	}
	first, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read first content failed: %v", err)
	}

	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("second upsert failed: %v", err)
	}
	second, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read second content failed: %v", err)
	}

	if string(first) != string(second) {
		t.Fatalf("expected equivalent rerun to be byte-identical")
	}
	firstInfo, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat first content failed: %v", err)
	}
	time.Sleep(20 * time.Millisecond)
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("third upsert failed: %v", err)
	}
	secondInfo, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat second content failed: %v", err)
	}
	if !firstInfo.ModTime().Equal(secondInfo.ModTime()) {
		t.Fatalf("expected equivalent rerun to avoid rewriting file")
	}
}

func TestUpsertDryRunLeavesExistingFileByteExact(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		"# user content",
		StartMarker,
		"old",
		EndMarker,
		"*.log",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"go"}, "bin/")
	action, err := m.UpsertManagedBlock(block, true)
	if err != nil {
		t.Fatalf("dry-run upsert failed: %v", err)
	}
	if action != FileActionDryRun {
		t.Fatalf("unexpected action: %s", action)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	if string(content) != seed {
		t.Fatalf("expected dry-run to preserve file exactly")
	}
}

func TestUpsertDedupRemovesExactDuplicateUnmanagedRule(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		".DS_Store",
		"*.log",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"macos"}, ".DS_Store\n")
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	value := string(content)

	if strings.Count(value, ".DS_Store") != 1 {
		t.Fatalf("expected duplicate unmanaged .DS_Store to be removed\n%s", value)
	}
	if !strings.Contains(value, "*.log") {
		t.Fatalf("expected non-duplicate unmanaged rules to remain\n%s", value)
	}
}

func TestUpsertDedupRemovesSafeEquivalentLeadingSlashForm(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		"/.DS_Store",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"macos"}, ".DS_Store\n")
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	value := string(content)

	if strings.Contains(value, "\n/.DS_Store\n") {
		t.Fatalf("expected unmanaged /.DS_Store to be deduped against managed .DS_Store\n%s", value)
	}
	if strings.Count(value, ".DS_Store") != 1 {
		t.Fatalf("expected only managed .DS_Store to remain\n%s", value)
	}
}

func TestUpsertDedupPreservesCommentsAndBlankLines(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		"# Keep this comment",
		"",
		".DS_Store",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"macos"}, strings.Join([]string{
		"# managed comment",
		".DS_Store",
		"",
	}, "\n"))
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	value := string(content)

	if !strings.Contains(value, "# Keep this comment") {
		t.Fatalf("expected unmanaged comment to be preserved\n%s", value)
	}
	if strings.Contains(value, "\n.DS_Store\n\n") {
		t.Fatalf("expected unmanaged duplicate .DS_Store to be removed\n%s", value)
	}
	if strings.Contains(value, "\n# managed comment\n# Keep this comment\n") {
		t.Fatalf("expected unmanaged comment not to be deduped using managed comment lines\n%s", value)
	}
}

func TestUpsertDedupPreservesAmbiguousSemanticDifference(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		"storage",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"generic"}, "storage/\n")
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	value := string(content)

	if !strings.Contains(value, "\nstorage\n") {
		t.Fatalf("expected unmanaged storage rule to remain because storage/ is not always equivalent\n%s", value)
	}
	if !strings.Contains(value, "\nstorage/\n") {
		t.Fatalf("expected managed storage/ rule to remain\n%s", value)
	}
}

func TestBuildManagedBlockAlwaysIncludesEnvIgnoreRules(t *testing.T) {
	t.Parallel()

	block := BuildManagedBlock([]string{"go"}, "bin/\n")

	for _, line := range []string{".env", ".env.*"} {
		if !strings.Contains(block, "\n"+line+"\n") {
			t.Fatalf("expected managed block to include %q\n%s", line, block)
		}
	}
}

func TestBuildManagedBlockAlwaysIncludesEnvExceptions(t *testing.T) {
	t.Parallel()

	block := BuildManagedBlock([]string{"go"}, "bin/\n")

	for _, line := range []string{"!.env.example", "!.env.ci"} {
		if !strings.Contains(block, "\n"+line+"\n") {
			t.Fatalf("expected managed block to include %q\n%s", line, block)
		}
	}
}

func TestUpsertEnvReconcilesExistingRulesDeterministically(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	seed := strings.Join([]string{
		"/.env",
		".env",
		".env",
		".env.*",
		"!.env.example",
		"!.env.ci",
		"!.env.local",
		"*.log",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(seed), 0o644); err != nil {
		t.Fatalf("seed file failed: %v", err)
	}

	m := NewManager(dir)
	block := BuildManagedBlock([]string{"go"}, "bin/\n")
	if _, err := m.UpsertManagedBlock(block, false); err != nil {
		t.Fatalf("upsert failed: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read .gitignore failed: %v", err)
	}
	value := string(content)

	for _, line := range []string{".env", ".env.*", "!.env.example", "!.env.ci"} {
		if countExactLine(value, line) != 1 {
			t.Fatalf("expected exactly one %q in reconciled output\n%s", line, value)
		}
	}
	if strings.Contains(value, "\n/.env\n") {
		t.Fatalf("expected rooted duplicate /.env to be reconciled\n%s", value)
	}
	if !strings.Contains(value, "\n!.env.local\n") {
		t.Fatalf("expected env-specific exception to remain represented\n%s", value)
	}
}

func TestUpsertEnvEquivalentRerunIsIdempotent(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, ".gitignore")
	m := NewManager(dir)

	firstBlock := BuildManagedBlock([]string{"go"}, strings.Join([]string{
		"bin/",
		"!.env.ci",
		".env.*",
		"!.env.example",
		".env",
		"",
	}, "\n"))
	if _, err := m.UpsertManagedBlock(firstBlock, false); err != nil {
		t.Fatalf("first upsert failed: %v", err)
	}
	firstContent, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read first content failed: %v", err)
	}
	firstInfo, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat first content failed: %v", err)
	}

	secondBlock := BuildManagedBlock([]string{"go"}, strings.Join([]string{
		"bin/",
		".env",
		"!.env.example",
		".env.*",
		"!.env.ci",
		"",
	}, "\n"))

	time.Sleep(20 * time.Millisecond)
	if _, err := m.UpsertManagedBlock(secondBlock, false); err != nil {
		t.Fatalf("second upsert failed: %v", err)
	}
	secondContent, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read second content failed: %v", err)
	}
	secondInfo, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat second content failed: %v", err)
	}

	if string(firstContent) != string(secondContent) {
		t.Fatalf("expected equivalent env content rerun to be byte-identical\nfirst:\n%s\nsecond:\n%s", string(firstContent), string(secondContent))
	}
	if !firstInfo.ModTime().Equal(secondInfo.ModTime()) {
		t.Fatalf("expected equivalent env content rerun to avoid rewriting file")
	}
}

func countExactLine(content, line string) int {
	count := 0
	for _, current := range strings.Split(content, "\n") {
		if current == line {
			count++
		}
	}
	return count
}
