package gitignore

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	StartMarker = "# BEGIN gitignore-gen"
	EndMarker   = "# END gitignore-gen"
)

type FileAction string

const (
	FileActionCreated FileAction = "created"
	FileActionUpdated FileAction = "updated"
	FileActionDryRun  FileAction = "dry-run"
)

type Manager struct {
	Path string
}

func NewManager(cwd string) *Manager {
	return &Manager{Path: filepath.Join(cwd, ".gitignore")}
}

func BuildManagedBlock(providers []string, template string) string {
	lines := []string{
		StartMarker,
		"# Generated by gitignore-gen. Do not edit between these markers.",
		"# Providers: " + strings.Join(providers, ","),
		strings.TrimRight(template, "\n"),
		EndMarker,
		"",
	}
	return strings.Join(lines, "\n")
}

func ParseManagedProviders(content string) []string {
	start := strings.Index(content, StartMarker)
	end := strings.Index(content, EndMarker)
	if start == -1 || end == -1 || end < start {
		return nil
	}
	block := content[start:end]
	for _, line := range strings.Split(block, "\n") {
		if strings.HasPrefix(line, "# Providers: ") {
			csv := strings.TrimPrefix(line, "# Providers: ")
			if csv == "" {
				return nil
			}
			return strings.Split(csv, ",")
		}
	}
	return nil
}

func (m *Manager) ReadManagedProviders() ([]string, error) {
	content, err := os.ReadFile(m.Path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .gitignore: %w", err)
	}
	return ParseManagedProviders(string(content)), nil
}

func (m *Manager) UpsertManagedBlock(block string, dryRun bool) (FileAction, error) {
	content, err := os.ReadFile(m.Path)
	if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("read .gitignore: %w", err)
	}

	if os.IsNotExist(err) {
		if dryRun {
			return FileActionDryRun, nil
		}
		if writeErr := os.WriteFile(m.Path, []byte(block), 0o644); writeErr != nil {
			return "", fmt.Errorf("create .gitignore: %w", writeErr)
		}
		return FileActionCreated, nil
	}

	existing := string(content)
	updated, mergeErr := mergeManagedBlock(existing, block)
	if mergeErr != nil {
		return "", mergeErr
	}
	if dryRun {
		return FileActionDryRun, nil
	}
	if updated == existing {
		return FileActionUpdated, nil
	}
	if writeErr := os.WriteFile(m.Path, []byte(updated), 0o644); writeErr != nil {
		return "", fmt.Errorf("update .gitignore: %w", writeErr)
	}
	return FileActionUpdated, nil
}

func mergeManagedBlock(existing, block string) (string, error) {
	start, end, hasMarkers, malformed := managedMarkerBounds(existing)
	if malformed {
		return "", fmt.Errorf("malformed managed markers in .gitignore: ensure exactly one %q and one %q in order", StartMarker, EndMarker)
	}
	if !hasMarkers {
		if existing == "" {
			return block, nil
		}
		if strings.HasSuffix(block, "\n") {
			return block + existing, nil
		}
		return block + "\n" + existing, nil
	}

	return existing[:start] + block + existing[end:], nil
}

func managedMarkerBounds(content string) (start int, end int, hasMarkers bool, malformed bool) {
	startCount := strings.Count(content, StartMarker)
	endCount := strings.Count(content, EndMarker)
	if startCount == 0 && endCount == 0 {
		return 0, 0, false, false
	}
	if startCount != 1 || endCount != 1 {
		return 0, 0, false, true
	}

	start = strings.Index(content, StartMarker)
	end = strings.Index(content, EndMarker)
	if end < start {
		return 0, 0, false, true
	}

	end += len(EndMarker)
	if end < len(content) && content[end] == '\n' {
		end++
	}

	return start, end, true, false
}
