package gitignore

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	StartMarker = "# BEGIN genignore"
	EndMarker   = "# END genignore"
)

type FileAction string

const (
	FileActionCreated FileAction = "created"
	FileActionUpdated FileAction = "updated"
	FileActionDryRun  FileAction = "dry-run"
)

type Manager struct {
	Path string
}

func NewManager(cwd string) *Manager {
	return &Manager{Path: filepath.Join(cwd, ".gitignore")}
}

func BuildManagedBlock(providers []string, template string) string {
	normalized := normalizeTemplate(template)
	lines := []string{
		StartMarker,
		"# Generated by genignore. Do not edit between these markers.",
		"# Providers: " + strings.Join(providers, ","),
		normalized,
		EndMarker,
		"",
	}
	return strings.Join(lines, "\n")
}

func normalizeTemplate(template string) string {
	lines := strings.Split(template, "\n")
	normalized := make([]string, 0, len(lines))
	for _, line := range lines {
		if isToptalBoilerplateComment(line) {
			continue
		}
		normalized = append(normalized, line)
	}

	return strings.Trim(strings.Join(normalized, "\n"), "\n")
}

func isToptalBoilerplateComment(line string) bool {
	trimmed := strings.TrimSpace(line)
	if !strings.HasPrefix(trimmed, "# ") {
		return false
	}

	return strings.HasPrefix(trimmed, "# Created by https://www.toptal.com/developers/gitignore/api/") ||
		strings.HasPrefix(trimmed, "# Edit at https://www.toptal.com/developers/gitignore?templates=") ||
		strings.HasPrefix(trimmed, "# End of https://www.toptal.com/developers/gitignore/api/")
}

func ParseManagedProviders(content string) []string {
	start := strings.Index(content, StartMarker)
	end := strings.Index(content, EndMarker)
	if start == -1 || end == -1 || end < start {
		return nil
	}
	block := content[start:end]
	for _, line := range strings.Split(block, "\n") {
		if strings.HasPrefix(line, "# Providers: ") {
			csv := strings.TrimPrefix(line, "# Providers: ")
			if csv == "" {
				return nil
			}
			return strings.Split(csv, ",")
		}
	}
	return nil
}

func (m *Manager) ReadManagedProviders() ([]string, error) {
	content, err := os.ReadFile(m.Path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .gitignore: %w", err)
	}
	return ParseManagedProviders(string(content)), nil
}

func (m *Manager) UpsertManagedBlock(block string, dryRun bool) (FileAction, error) {
	content, err := os.ReadFile(m.Path)
	if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("read .gitignore: %w", err)
	}

	if os.IsNotExist(err) {
		if dryRun {
			return FileActionDryRun, nil
		}
		if writeErr := os.WriteFile(m.Path, []byte(block), 0o644); writeErr != nil {
			return "", fmt.Errorf("create .gitignore: %w", writeErr)
		}
		return FileActionCreated, nil
	}

	existing := string(content)
	updated, mergeErr := mergeManagedBlock(existing, block)
	if mergeErr != nil {
		return "", mergeErr
	}
	if dryRun {
		return FileActionDryRun, nil
	}
	if updated == existing {
		return FileActionUpdated, nil
	}
	if writeErr := os.WriteFile(m.Path, []byte(updated), 0o644); writeErr != nil {
		return "", fmt.Errorf("update .gitignore: %w", writeErr)
	}
	return FileActionUpdated, nil
}

func mergeManagedBlock(existing, block string) (string, error) {
	start, end, hasMarkers, malformed := managedMarkerBounds(existing)
	if malformed {
		return "", fmt.Errorf("malformed managed markers in .gitignore: ensure exactly one %q and one %q in order", StartMarker, EndMarker)
	}
	managedRules := buildManagedRuleIndex(block)
	if !hasMarkers {
		existing = dedupeUnmanagedLines(existing, managedRules)
		if existing == "" {
			return block, nil
		}
		if strings.HasSuffix(block, "\n") {
			return block + existing, nil
		}
		return block + "\n" + existing, nil
	}

	prefix := dedupeUnmanagedLines(existing[:start], managedRules)
	suffix := dedupeUnmanagedLines(existing[end:], managedRules)
	return prefix + block + suffix, nil
}

type managedRuleIndex struct {
	exact                   map[string]struct{}
	unrootedLiteralBasename map[string]struct{}
	unrootedLiteralPath     map[string]struct{}
}

func buildManagedRuleIndex(block string) managedRuleIndex {
	index := managedRuleIndex{
		exact:                   make(map[string]struct{}),
		unrootedLiteralBasename: make(map[string]struct{}),
		unrootedLiteralPath:     make(map[string]struct{}),
	}

	for _, line := range strings.Split(block, "\n") {
		if !isRuleLine(line) {
			continue
		}

		index.exact[line] = struct{}{}
		if isUnrootedLiteralBasename(line) {
			index.unrootedLiteralBasename[line] = struct{}{}
		}
		if isUnrootedLiteralPath(line) {
			index.unrootedLiteralPath[line] = struct{}{}
		}
	}

	return index
}

func dedupeUnmanagedLines(content string, managed managedRuleIndex) string {
	if content == "" {
		return content
	}

	lines := strings.Split(content, "\n")
	filtered := make([]string, 0, len(lines))
	for _, line := range lines {
		if shouldRemoveAsManagedDuplicate(line, managed) {
			continue
		}
		filtered = append(filtered, line)
	}

	return strings.Join(filtered, "\n")
}

func shouldRemoveAsManagedDuplicate(line string, managed managedRuleIndex) bool {
	if !isRuleLine(line) {
		return false
	}
	if _, exists := managed.exact[line]; exists {
		return true
	}

	if strings.HasPrefix(line, "/") {
		candidate := strings.TrimPrefix(line, "/")
		if isUnrootedLiteralBasename(candidate) {
			_, exists := managed.unrootedLiteralBasename[candidate]
			return exists
		}
	}

	if strings.HasSuffix(line, "/") {
		candidate := strings.TrimSuffix(line, "/")
		if isUnrootedLiteralPath(candidate) {
			_, exists := managed.unrootedLiteralPath[candidate]
			return exists
		}
	}

	return false
}

func isRuleLine(line string) bool {
	trimmed := strings.TrimSpace(line)
	return trimmed != "" && !strings.HasPrefix(trimmed, "#")
}

func isUnrootedLiteralBasename(pattern string) bool {
	if pattern == "" || strings.HasPrefix(pattern, "/") || strings.Contains(pattern, "/") {
		return false
	}
	return !hasSpecialGlobChars(pattern)
}

func isUnrootedLiteralPath(pattern string) bool {
	if pattern == "" || strings.HasPrefix(pattern, "/") || strings.HasSuffix(pattern, "/") {
		return false
	}
	return !hasSpecialGlobChars(pattern)
}

func hasSpecialGlobChars(pattern string) bool {
	return strings.ContainsAny(pattern, "*?[\\!")
}

func managedMarkerBounds(content string) (start int, end int, hasMarkers bool, malformed bool) {
	startCount := strings.Count(content, StartMarker)
	endCount := strings.Count(content, EndMarker)
	if startCount == 0 && endCount == 0 {
		return 0, 0, false, false
	}
	if startCount != 1 || endCount != 1 {
		return 0, 0, false, true
	}

	start = strings.Index(content, StartMarker)
	end = strings.Index(content, EndMarker)
	if end < start {
		return 0, 0, false, true
	}

	end += len(EndMarker)
	if end < len(content) && content[end] == '\n' {
		end++
	}

	return start, end, true, false
}
