package gitignore

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	StartMarker = "# BEGIN genignore"
	EndMarker   = "# END genignore"
)

type FileAction string

const (
	FileActionCreated FileAction = "created"
	FileActionUpdated FileAction = "updated"
	FileActionNoOp    FileAction = "no-op"
	FileActionDryRun  FileAction = "dry-run"
)

type Manager struct {
	Path string
}

type Preview struct {
	Action FileAction
	Diff   string
}

func NewManager(cwd string) *Manager {
	return &Manager{Path: filepath.Join(cwd, ".gitignore")}
}

func BuildManagedBlock(providers []string, template string, extraRuleSources ...[]string) string {
	return BuildManagedBlockWithMetadata(providers, nil, template, extraRuleSources...)
}

func BuildManagedBlockWithMetadata(providers []string, metadata []string, template string, extraRuleSources ...[]string) string {
	normalized := normalizeTemplate(template, extraRuleSources...)
	lines := []string{
		StartMarker,
		"# Generated by genignore. Do not edit between these markers.",
		"# Providers: " + strings.Join(providers, ","),
	}
	for _, line := range metadata {
		if strings.TrimSpace(line) == "" {
			continue
		}
		lines = append(lines, line)
	}
	lines = append(lines, normalized, EndMarker, "")
	return strings.Join(lines, "\n")
}

var requiredEnvRules = []string{".env", ".env.*", "!.env.example", "!.env.ci"}

func normalizeTemplate(template string, extraRuleSources ...[]string) string {
	lines := strings.Split(template, "\n")
	normalized := make([]string, 0, len(lines))
	appended := make([]string, 0)
	envRules := make(map[string]struct{})
	ruleLines := make(map[string]struct{})

	for _, line := range lines {
		if isGeneratedSourceComment(line) {
			continue
		}
		if canonical, ok := canonicalizeEnvRule(line); ok {
			envRules[canonical] = struct{}{}
			continue
		}
		if isRuleLine(line) {
			ruleLines[strings.TrimSpace(line)] = struct{}{}
		}
		normalized = append(normalized, line)
	}

	for _, source := range extraRuleSources {
		for _, line := range source {
			trimmed := strings.TrimSpace(line)
			if trimmed == "" {
				continue
			}
			if canonical, ok := canonicalizeEnvRule(line); ok {
				envRules[canonical] = struct{}{}
				continue
			}
			if _, exists := ruleLines[trimmed]; exists {
				continue
			}
			ruleLines[trimmed] = struct{}{}
			appended = append(appended, trimmed)
		}
	}

	for _, required := range requiredEnvRules {
		envRules[required] = struct{}{}
	}

	trimmedNormalized := trimTrailingBlankLines(normalized)
	if len(appended) > 0 {
		if len(trimmedNormalized) > 0 && strings.TrimSpace(trimmedNormalized[len(trimmedNormalized)-1]) != "" {
			trimmedNormalized = append(trimmedNormalized, "")
		}
		trimmedNormalized = append(trimmedNormalized, appended...)
	}

	orderedEnvRules := orderedEnvRules(envRules)
	if len(orderedEnvRules) > 0 {
		if len(trimmedNormalized) > 0 && strings.TrimSpace(trimmedNormalized[len(trimmedNormalized)-1]) != "" {
			trimmedNormalized = append(trimmedNormalized, "")
		}
		trimmedNormalized = append(trimmedNormalized, orderedEnvRules...)
	}

	return strings.Trim(strings.Join(trimmedNormalized, "\n"), "\n")
}

func orderedEnvRules(envRules map[string]struct{}) []string {
	additional := make([]string, 0, len(envRules))
	for line := range envRules {
		if isRequiredEnvRule(line) || conflictsWithRequiredEnvRule(line) {
			continue
		}
		additional = append(additional, line)
	}
	sort.Strings(additional)

	ordered := make([]string, 0, len(requiredEnvRules)+len(additional))
	ordered = append(ordered, requiredEnvRules...)
	ordered = append(ordered, additional...)
	return ordered
}

func isRequiredEnvRule(line string) bool {
	for _, required := range requiredEnvRules {
		if line == required {
			return true
		}
	}
	return false
}

func conflictsWithRequiredEnvRule(line string) bool {
	switch line {
	case "!.env", "!.env.*", ".env.example", ".env.ci":
		return true
	default:
		return false
	}
}

func trimTrailingBlankLines(lines []string) []string {
	end := len(lines)
	for end > 0 && strings.TrimSpace(lines[end-1]) == "" {
		end--
	}
	return lines[:end]
}

func canonicalizeEnvRule(line string) (string, bool) {
	if !isRuleLine(line) {
		return "", false
	}

	trimmed := strings.TrimSpace(line)
	negated := strings.HasPrefix(trimmed, "!")
	if negated {
		trimmed = strings.TrimPrefix(trimmed, "!")
	}
	trimmed = strings.TrimPrefix(trimmed, "/")
	if !strings.HasPrefix(trimmed, ".env") {
		return "", false
	}

	if negated {
		return "!" + trimmed, true
	}
	return trimmed, true
}

func isGeneratedSourceComment(line string) bool {
	trimmed := strings.TrimSpace(line)
	if !strings.HasPrefix(trimmed, "# ") {
		return false
	}

	return strings.HasPrefix(trimmed, "# Created by https://www.toptal.com/developers/gitignore/api/") ||
		strings.HasPrefix(trimmed, "# Edit at https://www.toptal.com/developers/gitignore?templates=") ||
		strings.HasPrefix(trimmed, "# End of https://www.toptal.com/developers/gitignore/api/") ||
		strings.HasPrefix(trimmed, "# Source: github/gitignore/") ||
		strings.HasPrefix(trimmed, "# Source: https://raw.githubusercontent.com/github/gitignore/")
}

func ParseManagedProviders(content string) []string {
	start := strings.Index(content, StartMarker)
	end := strings.Index(content, EndMarker)
	if start == -1 || end == -1 || end < start {
		return nil
	}
	block := content[start:end]
	for _, line := range strings.Split(block, "\n") {
		if strings.HasPrefix(line, "# Providers: ") {
			csv := strings.TrimPrefix(line, "# Providers: ")
			if csv == "" {
				return nil
			}
			return strings.Split(csv, ",")
		}
	}
	return nil
}

func (m *Manager) ReadManagedProviders() ([]string, error) {
	content, err := os.ReadFile(m.Path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .gitignore: %w", err)
	}
	return ParseManagedProviders(string(content)), nil
}

func (m *Manager) PreviewManagedBlock(block string) (Preview, error) {
	change, err := m.planManagedBlockChange(block)
	if err != nil {
		return Preview{}, err
	}
	return Preview{Action: change.action, Diff: managedBlockDiff(change.currentBlock, block)}, nil
}

func (m *Manager) UpsertManagedBlock(block string, dryRun bool) (FileAction, error) {
	change, err := m.planManagedBlockChange(block)
	if err != nil {
		return "", err
	}

	if change.action == FileActionCreated {
		if dryRun {
			return FileActionDryRun, nil
		}
		if writeErr := os.WriteFile(m.Path, []byte(block), 0o644); writeErr != nil {
			return "", fmt.Errorf("create .gitignore: %w", writeErr)
		}
		return FileActionCreated, nil
	}
	if dryRun {
		return FileActionDryRun, nil
	}
	if change.action == FileActionNoOp {
		return FileActionNoOp, nil
	}
	if writeErr := os.WriteFile(m.Path, []byte(change.updatedContent), 0o644); writeErr != nil {
		return "", fmt.Errorf("update .gitignore: %w", writeErr)
	}
	return FileActionUpdated, nil
}

type plannedManagedBlockChange struct {
	action         FileAction
	currentBlock   string
	updatedContent string
}

func (m *Manager) planManagedBlockChange(block string) (plannedManagedBlockChange, error) {
	content, err := os.ReadFile(m.Path)
	if err != nil && !os.IsNotExist(err) {
		return plannedManagedBlockChange{}, fmt.Errorf("read .gitignore: %w", err)
	}

	if os.IsNotExist(err) {
		return plannedManagedBlockChange{action: FileActionCreated, updatedContent: block}, nil
	}

	existing := string(content)
	currentBlock, currentErr := currentManagedBlock(existing)
	if currentErr != nil {
		return plannedManagedBlockChange{}, currentErr
	}
	updated, mergeErr := mergeManagedBlock(existing, block)
	if mergeErr != nil {
		return plannedManagedBlockChange{}, mergeErr
	}
	if updated == existing {
		return plannedManagedBlockChange{action: FileActionNoOp, currentBlock: currentBlock, updatedContent: updated}, nil
	}
	return plannedManagedBlockChange{action: FileActionUpdated, currentBlock: currentBlock, updatedContent: updated}, nil
}

func mergeManagedBlock(existing, block string) (string, error) {
	start, end, hasMarkers, malformed := managedMarkerBounds(existing)
	if malformed {
		return "", fmt.Errorf("malformed managed markers in .gitignore: ensure exactly one %q and one %q in order", StartMarker, EndMarker)
	}
	if !hasMarkers {
		if existing == "" {
			return block, nil
		}
		if strings.HasSuffix(block, "\n") {
			return block + existing, nil
		}
		return block + "\n" + existing, nil
	}

	return existing[:start] + block + existing[end:], nil
}

func currentManagedBlock(content string) (string, error) {
	start, end, hasMarkers, malformed := managedMarkerBounds(content)
	if malformed {
		return "", fmt.Errorf("malformed managed markers in .gitignore: ensure exactly one %q and one %q in order", StartMarker, EndMarker)
	}
	if !hasMarkers {
		return "", nil
	}
	return content[start:end], nil
}

func managedBlockDiff(currentBlock, nextBlock string) string {
	if currentBlock == nextBlock {
		return ""
	}

	lines := []string{"--- .gitignore", "+++ .gitignore", "@@ managed-block @@"}
	for _, line := range diffLines(currentBlock) {
		lines = append(lines, "-"+line)
	}
	for _, line := range diffLines(nextBlock) {
		lines = append(lines, "+"+line)
	}
	return strings.Join(lines, "\n")
}

func diffLines(content string) []string {
	trimmed := strings.TrimSuffix(content, "\n")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "\n")
}

func isRuleLine(line string) bool {
	trimmed := strings.TrimSpace(line)
	return trimmed != "" && !strings.HasPrefix(trimmed, "#")
}

func isUnrootedLiteralBasename(pattern string) bool {
	if pattern == "" || strings.HasPrefix(pattern, "/") || strings.Contains(pattern, "/") {
		return false
	}
	return !hasSpecialGlobChars(pattern)
}

func isUnrootedLiteralPath(pattern string) bool {
	if pattern == "" || strings.HasPrefix(pattern, "/") || strings.HasSuffix(pattern, "/") {
		return false
	}
	return !hasSpecialGlobChars(pattern)
}

func hasSpecialGlobChars(pattern string) bool {
	return strings.ContainsAny(pattern, "*?[\\!")
}

func managedMarkerBounds(content string) (start int, end int, hasMarkers bool, malformed bool) {
	startCount := strings.Count(content, StartMarker)
	endCount := strings.Count(content, EndMarker)
	if startCount == 0 && endCount == 0 {
		return 0, 0, false, false
	}
	if startCount != 1 || endCount != 1 {
		return 0, 0, false, true
	}

	start = strings.Index(content, StartMarker)
	end = strings.Index(content, EndMarker)
	if end < start {
		return 0, 0, false, true
	}

	end += len(EndMarker)
	if end < len(content) && content[end] == '\n' {
		end++
	}

	return start, end, true, false
}
